/* brModelo - Lógico: */

CREATE TABLE CLIENTES (
    Cod_Cliente INTEIRO PRIMARY KEY,
    Sobrenome VARCHAR (50),
    Nome VARCHAR (50),
    Inicial CHAR (1),
    DDD VARCHAR (5),
    Telefone VARCHAR (15),
    Saldo DECIMAL
);

CREATE TABLE FATURAS (
    Num_Fatura INTEIRO PRIMARY KEY,
    Data_Fatura DATE,
    FK_CLIENTES_Cod_Cliente INTEIRO
);

CREATE TABLE LINHAS (
    Num_Linha INTEIRO PRIMARY KEY,
    Unidade INTEIRO,
    Valor DECIMAL,
    FK_FATURAS_Num_Fatura INTEIRO,
    FK_PRODUTOS_Cod_Produto INTEIRO
);

CREATE TABLE PRODUTOS (
    Cod_Produto INTEIRO PRIMARY KEY,
    Descricao VARCHAR (100),
    Data_Compra DATE,
    Quantidade INTEIRO,
    Valor DECIMAL,
    Desconto DECIMAL,
    FK_FORNECEDORES_Cod_Fornecedor INTEIRO
);

CREATE TABLE FORNECEDORES (
    Cod_Fornecedor INTEIRO PRIMARY KEY,
    Nome VARCHAR (60),
    Contato VARCHAR (20),
    DDD CHAR (5),
    Telefone VARCHAR (15),
    Estado VARCHAR (20),
    Cidade VARCHAR (50)
);
 
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2
    FOREIGN KEY (FK_CLIENTES_Cod_Cliente)
    REFERENCES CLIENTES (Cod_Cliente)
    ON DELETE CASCADE;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_2
    FOREIGN KEY (FK_FATURAS_Num_Fatura)
    REFERENCES FATURAS (Num_Fatura)
    ON DELETE RESTRICT;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_3
    FOREIGN KEY (FK_PRODUTOS_Cod_Produto)
    REFERENCES PRODUTOS (Cod_Produto)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_FORNECEDORES_Cod_Fornecedor)
    REFERENCES FORNECEDORES (Cod_Fornecedor)
    ON DELETE CASCADE;